// ============================================================
// De-AI Engine — Phrase Banks & Presets
// All detection strings are lowercase; matching is case-insensitive.
// ============================================================

import type { RewriteMode, EmotionMode } from "./types";

// ── Detection Banks ──────────────────────────────────────────

export const GENERIC_OPENERS: string[] = [
  "in today's world",
  "in today's fast-paced world",
  "in today's ever-changing world",
  "in today's digital world",
  "in the modern world",
  "in the digital age",
  "in recent years",
  "it is important to note",
  "it's important to note",
  "when it comes to",
  "most people think",
  "most people believe",
  "most people",
  "there are many reasons",
  "there are several reasons",
  "there are a number of",
  "in conclusion",
  "overall,",
  "to summarize",
  "in this article",
  "in this post",
  "in this blog",
  "in this piece",
  "as we all know",
  "it goes without saying",
  "needless to say",
  "we live in a world",
  "have you ever wondered",
  "imagine a world where",
  "picture this:",
  "let's dive in",
  "let's explore",
  "let us explore",
  "throughout history",
  "since the dawn of",
];

export const CONCLUSION_PHRASES: string[] = [
  "in conclusion",
  "to summarize",
  "in summary",
  "overall,",
  "to wrap up",
  "at the end of the day",
  "ultimately,",
  "to conclude",
  "as we have seen",
  "as discussed above",
  "as outlined above",
  "to recap",
  "in closing",
  "to bring it all together",
  "all in all,",
  "to put it all together",
  "the bottom line is",
  "when all is said and done",
];

export const TRANSITION_WORDS: string[] = [
  "first and foremost",
  "last but not least",
  "on the other hand",
  "in other words",
  "to put it simply",
  "with that said",
  "that being said",
  "having said that",
  "in light of this",
  "as a result",
  "in contrast",
  "in addition",
  "for instance",
  "for example",
  "furthermore",
  "additionally",
  "consequently",
  "nevertheless",
  "nonetheless",
  "therefore",
  "moreover",
  "however",
  "thus",
  "in turn",
  "given this",
];

export const TEACHING_TONE_MARKERS: string[] = [
  "it is important to understand that",
  "it's important to understand that",
  "it is important to understand",
  "it's important to understand",
  "it is important to note that",
  "it's important to note that",
  "it is important to note",
  "it's important to note",
  "it is crucial to understand",
  "it's crucial to understand",
  "it is worth noting that",
  "it's worth noting that",
  "it is worth noting",
  "it's worth noting",
  "it is worth mentioning that",
  "it's worth mentioning that",
  "what this means is",
  "this highlights the importance of",
  "this highlights the need for",
  "this highlights",
  "this demonstrates that",
  "this illustrates that",
  "this suggests that",
  "this shows that",
  "this means that",
  "this indicates that",
  "as we can see",
  "we can observe",
  "we can see that",
  "one must consider",
  "we must consider",
  "we need to understand",
  "you need to understand",
  "you should know",
  "keep in mind that",
  "keep in mind",
  "bear in mind that",
  "bear in mind",
  "it should be noted that",
  "it should be noted",
  "the key takeaway is",
  "the key takeaway",
  "the main takeaway",
  "let us explore",
  "let's explore",
  "here are",
  "here is",
];

export const FILLER_PHRASES: string[] = [
  "needless to say",
  "as you can imagine",
  "it is worth mentioning",
  "it's worth mentioning",
  "quite simply",
  "very simply",
  "undoubtedly",
  "definitely",
  "absolutely",
  "certainly",
  "obviously",
  "clearly",
  "frankly",
  "literally",
  "essentially",
  "basically",
  "actually",
  "simply",
  "really",
  "truly",
  "quite",
  "very",
  "just",
];

// Used to measure emotional intensity of text
export const EMOTIONAL_WORDS: string[] = [
  "hate", "love", "terrible", "awful", "amazing", "horrible", "incredible",
  "furious", "disgusted", "delighted", "appalled", "ecstatic", "miserable",
  "outraged", "thrilled", "devastated", "excited", "annoyed", "frustrated",
  "worried", "anxious", "angry", "surprised", "shocked", "confused",
  "disappointed", "proud", "ashamed", "jealous", "scared",
  "afraid", "hopeful", "desperate", "exhausted", "overwhelmed",
  "infuriating", "ridiculous", "absurd", "pathetic", "brilliant",
  "stunning", "breathtaking", "heartbreaking", "alarming", "disturbing",
];

// ── Grounded Openers by RewriteMode ─────────────────────────

export const GROUNDED_OPENERS: Record<RewriteMode, string[]> = {
  rawHuman: [
    "I keep seeing this.",
    "Saw this again today.",
    "Okay so.",
    "Here's the thing.",
    "This keeps coming up.",
    "Something's been bugging me about this.",
  ],
  frustratedRant: [
    "This is where it gets annoying.",
    "Honestly.",
    "No, seriously.",
    "I'm tired of this.",
    "Every single time.",
    "Can we just be real for a second?",
  ],
  founderVoice: [
    "Look, the real problem is this.",
    "We tried everything.",
    "Here's what nobody tells you:",
    "After going through this myself,",
    "The honest answer?",
    "What we actually found:",
  ],
  casualInternet: [
    "Weird thing is,",
    "So this happened.",
    "Real talk:",
    "Not gonna lie,",
    "Okay but actually —",
    "This caught me off guard.",
  ],
  sharpOpinion: [
    "The answer is obvious.",
    "Let me be direct.",
    "This is wrong.",
    "Nobody wants to say it, but",
    "Here's the actual truth:",
    "Stop pretending otherwise.",
  ],
};

// ── Emotional Phrases by EmotionMode ────────────────────────

export const EMOTIONAL_PHRASES: Record<EmotionMode, string[]> = {
  frustration: [
    "This keeps happening and it's exhausting.",
    "I've said this before and I'll say it again.",
    "It shouldn't be this hard.",
    "Every time. Every single time.",
  ],
  disbelief: [
    "I genuinely can't believe this is still a thing.",
    "How is this still happening?",
    "Wait, seriously?",
    "Still. In this year.",
  ],
  curiosity: [
    "Something about this doesn't add up.",
    "I've been thinking about this more than I should.",
    "There's a weird pattern here.",
    "The more I look at this, the stranger it gets.",
  ],
  confidence: [
    "I've seen enough to know the answer.",
    "This is not complicated.",
    "The data is clear on this.",
    "I'll say what others won't.",
  ],
  annoyance: [
    "Nobody asked, but here's the problem.",
    "This is the part that bothers me.",
    "It's the little things.",
    "This again.",
  ],
};

// ── Transition Replacement Map ───────────────────────────────
// Each entry: [light replacement, medium replacement, aggressive replacement]
// null = delete the word entirely

export const TRANSITION_REPLACEMENTS: Record<string, [string | null, string | null, string | null]> = {
  "first and foremost":  ["first",   null,    null],
  "last but not least":  ["finally", null,    null],
  "on the other hand":   ["but",     "but",   null],
  "in other words":      [null,      null,    null],
  "to put it simply":    [null,      null,    null],
  "with that said":      [null,      null,    null],
  "that being said":     [null,      null,    null],
  "having said that":    [null,      null,    null],
  "in light of this":    ["so",      null,    null],
  "as a result":         ["so",      "so",    null],
  "in contrast":         ["but",     "but",   null],
  "in addition":         ["also",    null,    null],
  "for instance":        ["like",    "like",  null],
  "for example":         ["like",    "like",  null],
  "furthermore":         ["also",    null,    null],
  "additionally":        ["also",    null,    null],
  "consequently":        ["so",      "so",    null],
  "nevertheless":        ["still",   "but",   null],
  "nonetheless":         ["still",   "but",   null],
  "therefore":           ["so",      "so",    null],
  "moreover":            ["also",    null,    null],
  "however":             ["but",     "but",   null],
  "thus":                ["so",      null,    null],
  "in turn":             [null,      null,    null],
  "given this":          ["so",      null,    null],
};

// ── Reality Anchors ──────────────────────────────────────────
// V2: Mandatory opening grounders — all rewrites must start from one of these
export const REALITY_ANCHORS: string[] = [
  "saw this yesterday",
  "keep seeing this again and again",
  "looked at this recently",
  "this keeps happening",
  "honestly",
  "weird thing is",
  "had this conversation again recently",
  "this came up again this week",
  "keep running into this",
  "saw this pattern play out again",
];

// ── Hard-banned phrases (Rule 6) ─────────────────────────────
// These must never appear in output. Engine strips them in a dedicated pass.
export const HARD_BANNED_PHRASES: string[] = [
  "in conclusion",
  "to summarize",
  "in summary",
  "to conclude",
  "it is important to",
  "it's important to",
  "it is important that",
  "it's important that",
  "widely considered",
  "widely regarded",
  "plays a critical role",
  "plays an important role",
  "plays a key role",
  "plays a vital role",
  "it goes without saying",
  "needless to say",
  "it should be noted",
  "it is worth noting that",
  "it's worth noting that",
  "it is safe to say",
  "it's safe to say",
  "at the end of the day",
  "as we all know",
  "first and foremost",
  "last but not least",
  "in today's",
  "in the modern era",
  "in the digital age",
  "in this day and age",
  "it is clear that",
  "it's clear that",
  "one can argue",
  "it can be argued",
  "there is no doubt",
  "without a doubt",
  "it is undeniable",
  "all in all",
  "to sum up",
  "in a nutshell",
];

// ── Conversational Injectors (Rule 8) ────────────────────────
// 1–2 of these get woven into the output to make it feel spoken.
// Keyed by emotion for tone consistency.
export const CONVERSATIONAL_INJECTORS: Record<EmotionMode, string[]> = {
  frustration: [
    "honestly,",
    "the thing is,",
    "look —",
    "and here's what gets me:",
    "no, seriously —",
    "the real issue is",
  ],
  disbelief: [
    "and somehow",
    "wait —",
    "the thing is,",
    "honestly,",
    "which is wild because",
    "i still can't believe",
  ],
  curiosity: [
    "the thing is,",
    "weirdly enough,",
    "here's what I keep coming back to:",
    "honestly,",
    "which makes you wonder —",
    "what's strange is",
  ],
  confidence: [
    "look —",
    "here's the thing:",
    "honestly,",
    "the answer is straightforward:",
    "and I mean this —",
    "the thing is,",
  ],
  annoyance: [
    "honestly,",
    "the thing is,",
    "and yet —",
    "come on —",
    "this is the part that gets me:",
    "no —",
  ],
};

// Sub-set of teaching markers used for the "over-explanation" issue check
export const EXPLANATORY_PHRASES: string[] = [
  "what this means is",
  "in other words",
  "to put it simply",
  "this means that",
  "this suggests that",
  "this shows that",
  "this demonstrates that",
  "this illustrates that",
  "this indicates that",
];

// ── Corporate Buzzwords ──────────────────────────────────────
// These are jargon words that AI uses to sound professional
export const CORPORATE_BUZZWORDS: string[] = [
  "leverage",
  "leveraging",
  "leveraged",
  "synergy",
  "synergies",
  "paradigm",
  "paradigm shift",
  "ecosystem",
  "scalable",
  "scalability",
  "robust",
  "streamline",
  "streamlined",
  "streamlining",
  "empower",
  "empowers",
  "empowering",
  "empowered",
  "transformative",
  "holistic",
  "actionable",
  "actionable insights",
  "impactful",
  "deliverable",
  "deliverables",
  "bandwidth",
  "cutting-edge",
  "best-in-class",
  "value-add",
  "value proposition",
  "low-hanging fruit",
  "move the needle",
  "circle back",
  "deep dive",
  "touch base",
  "thought leader",
  "thought leadership",
  "game-changer",
  "game-changing",
  "disruptive",
  "innovative solution",
  "innovative solutions",
  "utilize",
  "utilizes",
  "utilized",
  "utilizing",
  "utilization",
  "facilitate",
  "facilitates",
  "facilitated",
  "facilitating",
];

// ── Hedge Phrases ────────────────────────────────────────────
// AI hedges constantly to avoid committing to a position
export const HEDGE_PHRASES: string[] = [
  "it could be argued that",
  "it could be argued",
  "one might argue that",
  "one might argue",
  "one might say that",
  "one might say",
  "some might argue",
  "some might say",
  "it may be the case that",
  "it may be the case",
  "it is possible that",
  "it could be said that",
  "it could be said",
  "to some extent",
  "in many ways",
  "in some ways",
  "in a sense",
  "arguably,",
  "arguably",
  "potentially,",
  "potentially",
  "ostensibly",
  "conceivably",
  "it remains to be seen",
  "time will tell",
];

// ── Overused Adverbs ─────────────────────────────────────────
// AI relies on adverbs to inflate significance without adding specificity
export const OVERUSED_ADVERBS: string[] = [
  "consistently",
  "significantly",
  "effectively",
  "efficiently",
  "seamlessly",
  "inherently",
  "predominantly",
  "fundamentally",
  "particularly",
  "especially",
  "generally",
  "typically",
  "commonly",
  "ultimately",
  "previously",
  "continuously",
  "constantly",
  "considerably",
  "substantially",
  "remarkably",
  "notably",
  "increasingly",
  "progressively",
  "comprehensively",
];

// ── Word-level Synonym Substitution Map ──────────────────────
// Used in rewrite to swap buzzwords for plain human words
// Key = buzzword (lowercase), Value = plain replacement
export const SYNONYM_MAP: Record<string, string> = {
  "utilize":        "use",
  "utilizes":       "uses",
  "utilized":       "used",
  "utilizing":      "using",
  "utilization":    "use",
  "facilitate":     "help",
  "facilitates":    "helps",
  "facilitated":    "helped",
  "facilitating":   "helping",
  "demonstrate":    "show",
  "demonstrates":   "shows",
  "demonstrated":   "showed",
  "demonstrating":  "showing",
  "subsequently":   "then",
  "commence":       "start",
  "commences":      "starts",
  "commenced":      "started",
  "commencing":     "starting",
  "endeavor":       "effort",
  "endeavors":      "efforts",
  "numerous":       "many",
  "optimal":        "best",
  "optimally":      "well",
  "individuals":    "people",
  "innovative":     "new",
  "innovation":     "improvement",
  "innovations":    "improvements",
  "streamline":     "simplify",
  "streamlines":    "simplifies",
  "streamlined":    "simplified",
  "empower":        "help",
  "empowers":       "helps",
  "empowered":      "helped",
  "impactful":      "useful",
  "actionable":     "practical",
  "transformative": "major",
  "holistic":       "broad",
  "robust":         "strong",
  "scalable":       "flexible",
  "seamlessly":     "smoothly",
  "seamless":       "smooth",
  "leverage":       "use",
  "leverages":      "uses",
  "leveraged":      "used",
  "leveraging":     "using",
  "paradigm":       "model",
  "synergies":      "benefits",
  "deliverable":    "result",
  "deliverables":   "results",
  "bandwidth":      "capacity",
  "cutting-edge":   "modern",
  "game-changer":   "big shift",
  "game-changing":  "significant",
  "disruptive":     "new",
};
